### ISSUE TITLE
jtapi配置好之后登录提示403是为什么

### ISSUE THREAD

**Issue by codexss** [mariotaku/jtapi-legacy#2]
rt

**Comment by mariotaku** [comment]
请在报告中包括以下内容：
- 版本号jtapi
- 客户端及版本
- 填写API时的格式

**Comment by codexss** [comment]
0.5
安卓客户端最新版
https://api.t***i.appspot.com/1.1/
https://api.t***i.appspot.com/oauth/
代理用的影梭，手机没root，服务器自己搭建的，难不成是部署问题？

**Comment by mariotaku** [comment]
用SS就不需要API的吧？

目前用API只有两种方式：[Twidere](https://play.google.com/store/apps/details?id=org.mariotaku.twidere) 和 [UTwitterAPI](repo.xposed.info/module/org.mariotaku.utwitterapi)

这两个地址是在哪里填写的？

**Comment by codexss** [comment]
Twidere，照着官方wiki弄得，有api不是要登录时翻墙吗，登录提示403错误

**Comment by mariotaku** [comment]
你试试打开 https://[your-app-id].appspot.com/ 看看，有没有内容？

**Comment by codexss** [comment]
重新配置了下可以了，应该是上传问题，关闭吧。
