### ISSUE TITLE
jtapi 0.5及0.6版本500错误

### ISSUE THREAD

**Issue by sacrish** [mariotaku/jtapi-legacy#3]
在一个新建的gapp上部署jtapi，0.5和0.6上传完毕后访问app页面均返回500错误，在twidere上尝试连接该api会提示url有误。0.3版本则可以正常使用。

**Comment by legendtang** [comment]
状况完全相同，不过看起来宅撩准备开新坑了？

**Comment by mariotaku** [comment]
yep，试试这个 https://github.com/TwidereProject/Twidere-API-Proxy-Go

**Comment by sacrish** [comment]
成功啦！宅撩我爱你啊！ヾ(´ε`ヾ)
